# Generated by Django 2.2 on 2021-01-09 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artists',
            old_name='county',
            new_name='country',
        ),
    ]
