# Generated by Django 2.2 on 2021-01-08 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='nombre')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, verbose_name='slug')),
                ('duration', models.PositiveIntegerField(verbose_name='')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albums.Albums', verbose_name='album')),
            ],
            options={
                'verbose_name': 'Canción',
                'verbose_name_plural': 'Canciones',
            },
        ),
    ]
